### ISSUE TITLE
Weird things...

### ISSUE THREAD

**Issue by fuad00** [Benitmulindwa/FletifyHTML#3]
<img width="997" alt="CleanShot 2024-01-31 at 02 10 55@2x" src="https://github.com/Benitmulindwa/FletifyHTML/assets/26776550/47b878e1-e28f-4c6e-884d-0498d3154534">

why i can't see Text1 ?

**Comment by Benitmulindwa** [comment]
Let me take a look!

**Comment by Benitmulindwa** [comment]
@fuad00 Put them inside a **Div** tag .
